/**
 * Independent New Zealand geographic datasets for PureNest Domestic Cleaning inspection form.
 * 
 * Free-flow two-dropdown model based on the reference QualGroup location UX:
 * - REGIONS: 16 New Zealand regions
 * - DISTRICTS: Comprehensive, independent list of New Zealand districts, cities,
 *   and popular local authority areas (including Auckland regional subdivisions from reference UX).
 * 
 * Both dropdowns are independent and free-flow.
 */

export const REGIONS = [
  'Northland',
  'Auckland',
  'Waikato',
  'Bay of Plenty',
  'Gisborne',
  'Hawke\'s Bay',
  'Taranaki',
  'Manawatū-Whanganui',
  'Wellington',
  'Tasman',
  'Nelson',
  'Marlborough',
  'West Coast',
  'Canterbury',
  'Otago',
  'Southland',
];

export const DISTRICTS = [
  'Ashburton District',
  'Auckland City',
  'Buller District',
  'Carterton District',
  'Central Hawke\'s Bay District',
  'Central Otago District',
  'Christchurch City',
  'Clutha District',
  'Dunedin City',
  'Far North District',
  'Franklin',
  'Gisborne District',
  'Gore District',
  'Grey District',
  'Hamilton City',
  'Hastings District',
  'Hauraki District',
  'Hauraki Gulf Islands',
  'Horowhenua District',
  'Hurunui District',
  'Invercargill City',
  'Kaikōura District',
  'Kaipara District',
  'Kāpiti Coast District',
  'Kawerau District',
  'Lower Hutt City',
  'Mackenzie District',
  'Manawatū District',
  'Manukau City',
  'Marlborough District',
  'Masterton District',
  'Matamata-Piako District',
  'Napier City',
  'Nelson City',
  'New Plymouth District',
  'North Shore City',
  'Ōpōtiki District',
  'Ōtorohanga District',
  'Palmerston North City',
  'Papakura',
  'Porirua City',
  'Queenstown-Lakes District',
  'Rangitīkei District',
  'Rodney',
  'Rotorua District',
  'Ruapehu District',
  'Selwyn District',
  'South Taranaki District',
  'South Waikato District',
  'South Wairarapa District',
  'Southland District',
  'Stratford District',
  'Tararua District',
  'Tasman District',
  'Taupō District',
  'Tauranga City',
  'Thames-Coromandel District',
  'Timaru District',
  'Upper Hutt City',
  'Waiheke Island',
  'Waikato District',
  'Waimakariri District',
  'Waimate District',
  'Waipā District',
  'Wairoa District',
  'Waitakere City',
  'Waitaki District',
  'Waitomo District',
  'Wellington City',
  'Western Bay of Plenty District',
  'Westland District',
  'Whakatāne District',
  'Whanganui District',
  'Whangārei District',
];
